import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import LandingPage from "./pages/LandingPage";
import AuthPage from "./pages/AuthPage";
import DashboardPage from "./pages/DashboardPage";
import "./style.css";
export const api = async (url, options = {}) => { const token = localStorage.getItem("campuscare_token"); const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "Request failed."); return data; };
function App() { const [user, setUser] = useState(null); const [complaints, setComplaints] = useState([]); const [stats, setStats] = useState({}); const [meta, setMeta] = useState({ categories: [], priorities: [], statuses: [] }); const [view, setView] = useState("landing"); const [loading, setLoading] = useState(true); const load = async () => { const [items, totals, options] = await Promise.all([api("/api/complaints"), api("/api/complaints/stats"), api("/api/complaints/meta")]); setComplaints(items); setStats(totals); setMeta(options); }; useEffect(() => { if (!localStorage.getItem("campuscare_token")) { setLoading(false); return; } api("/api/auth/me").then(({ user: account }) => setUser(account)).catch(() => localStorage.removeItem("campuscare_token")).finally(() => setLoading(false)); }, []); useEffect(() => { if (user) load().catch(() => {}).finally(() => setLoading(false)); }, [user]); if (loading && !user) return <main className="loading-screen">Loading CampusCare...</main>; if (!user) return view === "landing" ? <LandingPage onChoose={setView} /> : <AuthPage mode={view} onBack={() => setView("landing")} onLogin={setUser} />; return <DashboardPage user={user} complaints={complaints} stats={stats} meta={meta} refresh={load} onLogout={() => { localStorage.removeItem("campuscare_token"); setUser(null); setComplaints([]); setStats({}); setView("landing"); }} />; }
createRoot(document.getElementById("root")).render(<App />);
